---
# https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng
# https://www.brightbox.com/docs/ruby/ubuntu/
- name: add ruby nextgen repository
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: install essential packages
  apt: pkg={{item}} state={{compass_ruby_state}} update_cache=yes cache_valid_time=3600
  with_items:
    - ruby2.4
    - ruby2.4-dev
    - build-essential

- name: install gem compass
  become: yes
  become_user: root
  command: gem install compass